github workflow: use working-directory

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -34,6 +34,7 @@ jobs:
         with:
           python-version: '3.x'
       - name: Install dependencies
+        working-directory: $GITHUB_WORKSPACE/${{ env.ROLEPATH }}
         run: |
           python3 -m pip install --upgrade pip
           pip3 install ansible-lint flake8 yamllint
@@ -44,7 +45,6 @@ jobs:
           ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
           echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
           ansible --version
-          cd $GITHUB_WORKSPACE/${{ env.ROLEPATH }}
           { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
           ansible-galaxy install -r requirements.yml
       - name: Environment
@@ -53,17 +53,20 @@ jobs:
           env
           find -ls
       - name: run test
+        working-directory: $GITHUB_WORKSPACE/${{ env.ROLEPATH }}
         run: |
-          cd $GITHUB_WORKSPACE/${{ env.ROLEPATH }} && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
+          ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
+        working-directory: $GITHUB_WORKSPACE/${{ env.ROLEPATH }}
         run: |
-          cd $GITHUB_WORKSPACE/${{ env.ROLEPATH }} && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
       - name: verify
+        working-directory: $GITHUB_WORKSPACE/${{ env.ROLEPATH }}
         run: |
-          cd $GITHUB_WORKSPACE/${{ env.ROLEPATH }} && ansible-playbook -i localhost, --connection=local --become -v molecule/default/verify.yml ${ANSIBLE_EXTRA_VARS}
+          ansible-playbook -i localhost, --connection=local --become -v molecule/default/verify.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
